### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Getquanty/gtm-templates-zapier#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) User instructions to install the template should direct users to install the gallery version of the template by clicking on the "Search Gallery" button in the template tab to add the gallery template.
2) The documentation [link](https://getquanty.zendesk.com/hc/fr/articles/360016082693-Installer-le-script-GetQuanty-via-Google-Tag-Manager-GTM-) provided in manifest file is behind login screen. We are unable to see any data if present on the page.

**Comment by vg-getquanty** [comment]
Hi,

We just updated the documentation with public access.

Can you validate our proposal for GTM please ?

Best regards,
Valentin from GetQuanty
